-- c1   
ALTER TABLE CAUTHU WITH NOCHECK
ADD CONSTRAINT CHK_VITRI 
CHECK (VITRI IN (N'Thủ môn', N'Tiền đạo', N'Tiền vệ', N'Trung vệ', N'Hậu vệ'));

-- c2
ALTER TABLE HLV_CLB WITH NOCHECK
ADD CONSTRAINT CHK_VAITRO 
CHECK (VAITRO IN (N'HLV chính', N'HLV phụ', N'HLV thể lực', N'HLV thủ môn'));

-- c3 
ALTER TABLE CAUTHU WITH NOCHECK
ADD CONSTRAINT CHK_TUOI 
CHECK (2024 - YEAR(NGAYSINH) >= 18);

-- c4 
ALTER TABLE TRANDAU WITH NOCHECK
ADD CONSTRAINT CHK_KETQUA 
CHECK (KETQUA LIKE '%-%');

-- check command
SELECT name, type_desc, OBJECT_NAME(parent_object_id) AS TableName
FROM sys.check_constraints;

-- d1
CREATE VIEW V_D1 AS
SELECT CT.MACT, CT.HOTEN, CT.NGAYSINH, CT.DIACHI, CT.VITRI
FROM CAUTHU CT, CAULACBO CLB, QUOCGIA QG
WHERE CT.MACLB = CLB.MACLB
  AND CT.MAQG = QG.MAQG
  AND CLB.TENCLB = N'SHB ĐÀ NẴNG' 
  AND QG.TENQG = N'Brazil';

-- d2 
CREATE VIEW V_D2 AS
SELECT MATRAN, NGAYTD, TENSAN, C1.TENCLB AS TENCLB1, C2.TENCLB AS TENCLB2, KETQUA
FROM TRANDAU TD, SANVD S, CAULACBO C1, CAULACBO C2
WHERE TD.MASAN = S.MASAN 
  AND TD.MACLB1 = C1.MACLB 
  AND TD.MACLB2 = C2.MACLB
  AND VONG = 3 AND NAM = 2009;

-- d3 
CREATE VIEW V_D3 AS
SELECT HLV.MAHLV, TENHLV, NGAYSINH, DIACHI, VAITRO, TENCLB
FROM HUANLUYENVIEN HLV, HLV_CLB HC, CAULACBO CLB, QUOCGIA QG
WHERE HLV.MAHLV = HC.MAHLV 
  AND HC.MACLB = CLB.MACLB 
  AND HLV.MAQG = QG.MAQG
  AND TENQG = N'Việt Nam';

-- d4 
CREATE VIEW V_D4 AS
SELECT C.MACLB, TENCLB, TENSAN, S.DIACHI, COUNT(MACT) AS SOLUONG
FROM CAULACBO C, SANVD S, CAUTHU CT
WHERE C.MASAN = S.MASAN AND C.MACLB = CT.MACLB
  AND CT.MAQG <> 'VN'
GROUP BY C.MACLB, TENCLB, TENSAN, S.DIACHI
HAVING COUNT(MACT) > 2;

-- d5 
CREATE VIEW V_D5 AS
SELECT TENTINH, COUNT(MACT) AS SO_LUONG_TIEN_DAO
FROM TINH T, CAULACBO CLB, CAUTHU CT
WHERE T.MATINH = CLB.MATINH 
  AND CLB.MACLB = CT.MACLB
  AND VITRI = N'Tiền đạo'
GROUP BY TENTINH;

-- d6 
CREATE VIEW V_D6 AS
SELECT TENCLB, TENTINH
FROM BANGXH BXH, CAULACBO CLB, TINH T
WHERE BXH.MACLB = CLB.MACLB 
  AND CLB.MATINH = T.MATINH
  AND VONG = 3 AND NAM = 2009 AND HANG = 1;

-- d7 
CREATE VIEW V_D7 AS
SELECT TENHLV
FROM HUANLUYENVIEN HLV, HLV_CLB HC
WHERE HLV.MAHLV = HC.MAHLV
  AND DIENTHOAI IS NULL;

-- d8 
-- CREATE VIEW V_D8 AS
SELECT TENHLV
FROM HUANLUYENVIEN HLV, QUOCGIA QG
WHERE HLV.MAQG = QG.MAQG
  AND TENQG = N'Việt Nam'
  AND MAHLV NOT IN (SELECT MAHLVAND MAHLV NOT IN (SELECT MAHLV FROM HLV_CLB);